/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package editeur_assistance;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JColorChooser;
import org.jdom.Element;

/**
 *
 * @author Blandine
 */
public class MiseEnValeurPasAPas extends javax.swing.JFrame {

    Element elementMiseEnValeur;
    /**
     * Creates new form MiseEnValeurPasAPas
     */
    public MiseEnValeurPasAPas() {
        initComponents();
        
        this.setLayout(null);
        this.setBounds(200, 200, 700, 250);
    }
    
    public void chargerInterface()
    {
        Image icon = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/images/icone_editeur.png"));
        this.setIconImage(icon);
        ChargerLangue();
        
        PanelEntourerActionMiseEnValeur.setBounds(0, 0, this.getWidth(), this.getHeight());
        PanelEntourerActionMiseEnValeur.setLayout(null);
        LbEntourerCouleurActionMiseEnValeur.setBounds(10, 20, 150, 24);
        BtEntourerCouleurActionMiseEnValeur.setBounds(160, 20, 40, 24);
        BtEntourerCouleurActionMiseEnValeur.setBackground(FonctionsUtiles.StringToColor(elementMiseEnValeur.getChild("composant").getAttributeValue("couleur")));
        LbArrondiActionMiseEnValeur.setBounds(10, 50, 180, 24);
        SpinArrondiActionMiseEnValeur.setBounds(190, 50, 45, 24);
        SpinArrondiActionMiseEnValeur.setValue(Integer.parseInt(elementMiseEnValeur.getChild("composant").getAttributeValue("arrondi")));
        LbEloignementActionMiseEnValeur.setBounds(10, 90, 180, 24);
        SpinEloignementActionMiseEnValeur.setBounds(190, 90, 45, 24);
        SpinEloignementActionMiseEnValeur.setValue(Integer.parseInt(elementMiseEnValeur.getChild("composant").getAttributeValue("eloignement")));
        LbEpaisseurActionMiseEnValeur.setBounds(10, 130, 180, 24);
        SpinEpaisseurActionMiseEnValeur.setBounds(190, 130, 45, 24);
        SpinEpaisseurActionMiseEnValeur.setValue(Integer.parseInt(elementMiseEnValeur.getChild("composant").getAttributeValue("epaisseur")));
        
        BtValider.setBounds(120, this.getHeight()-80, 120, 30);
        BtApercu.setBounds(250, this.getHeight()-80, 120, 30);
        BtAnnuler.setBounds(380, this.getHeight()-80, 120, 30); 
    }
    
    private void ChargerLangue()
    {
        XMLFonctions.OuvrirXML(Main.Cste.fichierInterfaceEditeur);
        Element courant= (Element) XMLFonctions.racine.getChild("Communs").getChild("Titre").getChild(Main.Cste.langue);
        Element courant2= (Element) XMLFonctions.racine.getChild("miseEnValeurPasAPas").getChild("Titre").getChild(Main.Cste.langue);
        this.setTitle(courant.getText()+courant2.getText());
        
        courant= (Element) XMLFonctions.racine.getChild("miseEnValeurPasAPas").getChild("LbEntourerCouleurActionMiseEnValeur").getChild(Main.Cste.langue);
        LbEntourerCouleurActionMiseEnValeur.setText(courant.getText());
        courant= (Element) XMLFonctions.racine.getChild("miseEnValeurPasAPas").getChild("LbArrondiActionMiseEnValeur").getChild(Main.Cste.langue);
        LbArrondiActionMiseEnValeur.setText(courant.getText());
        courant= (Element) XMLFonctions.racine.getChild("miseEnValeurPasAPas").getChild("LbEloignementActionMiseEnValeur").getChild(Main.Cste.langue);
        LbEloignementActionMiseEnValeur.setText(courant.getText());
        courant= (Element) XMLFonctions.racine.getChild("miseEnValeurPasAPas").getChild("LbEpaisseurActionMiseEnValeur").getChild(Main.Cste.langue);
        LbEpaisseurActionMiseEnValeur.setText(courant.getText());
        
        courant= (Element) XMLFonctions.racine.getChild("Communs").getChild("BtAnnuler").getChild(Main.Cste.langue);
        BtAnnuler.setText(courant.getText());       
        courant= (Element) XMLFonctions.racine.getChild("Communs").getChild("BtValider").getChild(Main.Cste.langue);
        BtValider.setText(courant.getText()); 
        courant= (Element) XMLFonctions.racine.getChild("Communs").getChild("BtApercu").getChild(Main.Cste.langue);
        BtApercu.setText(courant.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEntourerActionMiseEnValeur = new javax.swing.JPanel();
        LbEntourerCouleurActionMiseEnValeur = new javax.swing.JLabel();
        BtEntourerCouleurActionMiseEnValeur = new javax.swing.JButton();
        LbArrondiActionMiseEnValeur = new javax.swing.JLabel();
        SpinArrondiActionMiseEnValeur = new javax.swing.JSpinner();
        LbEloignementActionMiseEnValeur = new javax.swing.JLabel();
        SpinEloignementActionMiseEnValeur = new javax.swing.JSpinner();
        LbEpaisseurActionMiseEnValeur = new javax.swing.JLabel();
        SpinEpaisseurActionMiseEnValeur = new javax.swing.JSpinner();
        BtValider = new javax.swing.JButton();
        BtApercu = new javax.swing.JButton();
        BtAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 225, 196));

        PanelEntourerActionMiseEnValeur.setBackground(new java.awt.Color(255, 225, 196));

        LbEntourerCouleurActionMiseEnValeur.setText("Couleur du trait");

        BtEntourerCouleurActionMiseEnValeur.setBackground(new java.awt.Color(255, 51, 51));
        BtEntourerCouleurActionMiseEnValeur.setText(" ");
        BtEntourerCouleurActionMiseEnValeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEntourerCouleurActionMiseEnValeurActionPerformed(evt);
            }
        });

        LbArrondiActionMiseEnValeur.setText("Arrondi");

        SpinArrondiActionMiseEnValeur.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        SpinArrondiActionMiseEnValeur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinArrondiActionMiseEnValeurStateChanged(evt);
            }
        });
        SpinArrondiActionMiseEnValeur.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SpinArrondiActionMiseEnValeurPropertyChange(evt);
            }
        });

        LbEloignementActionMiseEnValeur.setText("Distance trait/composant");

        SpinEloignementActionMiseEnValeur.setModel(new javax.swing.SpinnerNumberModel(0, -20, 20, 1));
        SpinEloignementActionMiseEnValeur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinEloignementActionMiseEnValeurStateChanged(evt);
            }
        });

        LbEpaisseurActionMiseEnValeur.setText("Epaisseur du trait");

        SpinEpaisseurActionMiseEnValeur.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));
        SpinEpaisseurActionMiseEnValeur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinEpaisseurActionMiseEnValeurStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PanelEntourerActionMiseEnValeurLayout = new javax.swing.GroupLayout(PanelEntourerActionMiseEnValeur);
        PanelEntourerActionMiseEnValeur.setLayout(PanelEntourerActionMiseEnValeurLayout);
        PanelEntourerActionMiseEnValeurLayout.setHorizontalGroup(
            PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntourerActionMiseEnValeurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LbEloignementActionMiseEnValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(LbArrondiActionMiseEnValeur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEntourerCouleurActionMiseEnValeur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEpaisseurActionMiseEnValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpinArrondiActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtEntourerCouleurActionMiseEnValeur)
                    .addComponent(SpinEloignementActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinEpaisseurActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEntourerActionMiseEnValeurLayout.setVerticalGroup(
            PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntourerActionMiseEnValeurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelEntourerActionMiseEnValeurLayout.createSequentialGroup()
                        .addComponent(LbEntourerCouleurActionMiseEnValeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbArrondiActionMiseEnValeur))
                    .addGroup(PanelEntourerActionMiseEnValeurLayout.createSequentialGroup()
                        .addComponent(BtEntourerCouleurActionMiseEnValeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinArrondiActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEloignementActionMiseEnValeur)
                    .addComponent(SpinEloignementActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEntourerActionMiseEnValeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEpaisseurActionMiseEnValeur)
                    .addComponent(SpinEpaisseurActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        BtValider.setText("Valider");
        BtValider.setToolTipText("Valider l'action et revenir à la définition des règles d'assistance");
        BtValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtValiderActionPerformed(evt);
            }
        });

        BtApercu.setText("Aperçu");
        BtApercu.setToolTipText("Voir un aperçu de la mise en valeur définie sur des composants exemples");
        BtApercu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtApercuActionPerformed(evt);
            }
        });

        BtAnnuler.setText("Annuler");
        BtAnnuler.setToolTipText("Retour à la définition des règles d'assistance");
        BtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(BtValider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtApercu)
                .addGap(18, 18, 18)
                .addComponent(BtAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(PanelEntourerActionMiseEnValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelEntourerActionMiseEnValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtValider)
                    .addComponent(BtApercu)
                    .addComponent(BtAnnuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtEntourerCouleurActionMiseEnValeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntourerCouleurActionMiseEnValeurActionPerformed
        BtEntourerCouleurActionMiseEnValeur.setBackground(JColorChooser.showDialog(this, "Choisir une couleur", BtEntourerCouleurActionMiseEnValeur.getBackground()));
        this.repaint();
    }//GEN-LAST:event_BtEntourerCouleurActionMiseEnValeurActionPerformed

    private void SpinArrondiActionMiseEnValeurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinArrondiActionMiseEnValeurStateChanged
        this.repaint();
    }//GEN-LAST:event_SpinArrondiActionMiseEnValeurStateChanged

    private void SpinArrondiActionMiseEnValeurPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SpinArrondiActionMiseEnValeurPropertyChange

   }//GEN-LAST:event_SpinArrondiActionMiseEnValeurPropertyChange

    private void SpinEloignementActionMiseEnValeurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinEloignementActionMiseEnValeurStateChanged
        this.repaint();
    }//GEN-LAST:event_SpinEloignementActionMiseEnValeurStateChanged

    private void SpinEpaisseurActionMiseEnValeurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinEpaisseurActionMiseEnValeurStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinEpaisseurActionMiseEnValeurStateChanged

    private void BtValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtValiderActionPerformed
        Element mis=new Element("miseEnValeur");
        Element compo = new Element("composant");
        compo.setAttribute("type", "entourer");
        compo.setAttribute("couleur", BtEntourerCouleurActionMiseEnValeur.getBackground().toString());
        compo.setAttribute("arrondi", SpinArrondiActionMiseEnValeur.getValue().toString());
        compo.setAttribute("eloignement", SpinEloignementActionMiseEnValeur.getValue().toString());
        compo.setAttribute("epaisseur", SpinEpaisseurActionMiseEnValeur.getValue().toString());
        mis.addContent(compo);
        Main.CreationActions.elementMiseEnValeurEtape=mis;
        this.setVisible(false);
    }//GEN-LAST:event_BtValiderActionPerformed

    private void BtApercuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtApercuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtApercuActionPerformed

    private void BtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BtAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiseEnValeurPasAPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiseEnValeurPasAPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiseEnValeurPasAPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiseEnValeurPasAPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MiseEnValeurPasAPas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAnnuler;
    private javax.swing.JButton BtApercu;
    private javax.swing.JButton BtEntourerCouleurActionMiseEnValeur;
    private javax.swing.JButton BtValider;
    private javax.swing.JLabel LbArrondiActionMiseEnValeur;
    private javax.swing.JLabel LbEloignementActionMiseEnValeur;
    private javax.swing.JLabel LbEntourerCouleurActionMiseEnValeur;
    private javax.swing.JLabel LbEpaisseurActionMiseEnValeur;
    private javax.swing.JPanel PanelEntourerActionMiseEnValeur;
    private javax.swing.JSpinner SpinArrondiActionMiseEnValeur;
    private javax.swing.JSpinner SpinEloignementActionMiseEnValeur;
    private javax.swing.JSpinner SpinEpaisseurActionMiseEnValeur;
    // End of variables declaration//GEN-END:variables
}
